Note endianness of 16-bit immediate values
gbdev/gb-opcodes pull request #23
Opened 2021-09-02 19:43 UTC by martendo

2021-09-02 19:46 UTC, ISSOtm requested changes

2021-09-02 19:46 UTC, ISSOtm commented on _includes/optables/description.html
> +				<p><kbd>d16</kbd> means immediate 16-bit data, in little endian</p>
```suggestion
				<p><kbd>d16</kbd> means immediate little-endian 16-bit data</p>
```

2021-09-02 19:46 UTC, ISSOtm commented on _includes/optables/description.html
> +				<p><kbd>a16</kbd> means 16-bit address, in little endian</p>
```suggestion
				<p><kbd>a16</kbd> means little-endian 16-bit address</p>
```

2021-09-02 19:47 UTC, ISSOtm approved these changes

2021-09-17 07:50 UTC, avivace approved these changes

2021-09-17 07:50 UTC, merged