Update RGBASM link
gbdev/gb-opcodes pull request #35
Opened 2024-01-22 19:36 UTC by Peeda

2024-01-22 19:42 UTC, ISSOtm requested changes
Oh, good catch. But there's an even better way: this link will always redirect to the latest version! Sorry, I don't think it's documented anywhere.

2024-01-22 19:42 UTC, ISSOtm commented on _includes/opcode-reference.html
> +	<a class="nav-link" href="https://rgbds.gbdev.io/docs/v0.7.0/gbz80.7/">Opcode reference</a>
```suggestion
	<a class="nav-link" href="https://rgbds.gbdev.io/docs/gbz80.7">Opcode reference</a>
```

2024-01-24 09:07 UTC, avivace approved these changes

2024-01-30 11:02 UTC, ISSOtm approved these changes
Nice. Thank you!

2024-01-30 11:02 UTC, merged